apiVersion: v1
data:
  client_id: U2V4bEVVVE1jS1hHcXlSRktRekI=
  client_secret: VndqRVgyeDNDNk9QbUZGcXZyNlQ=
kind: Secret
metadata:
  creationTimestamp: "2021-11-15T17:22:44Z"
  labels:
    app: icp4adeploy-graphql-oidc-secret
    app.kubernetes.io/instance: icp4adeploy
    app.kubernetes.io/managed-by: icp4adeploy
    app.kubernetes.io/name: icp4adeploy
    release: 21.0.2
  name: icp4adeploy-graphql-oidc-secret
  namespace: ssotest
  ownerReferences:
  - apiVersion: icp4a.ibm.com/v1
    kind: ICP4ACluster
    name: icp4adeploy
    uid: ef2680be-27d0-44eb-9e98-25455d453ba5
  resourceVersion: "73876393"
  uid: 54e2a65b-830c-4c66-9da6-126c42c1e04c
type: Opaque
