#!/bin/bash
# Add LDAP Bind user and passwort to the "ldap-bind-secret"
oc create secret generic ldap-lds-bind-secret --from-literal=ldapUsername="CN=eIAM-ESTV-EASY-BindUser,CN=Users,CN=Admin,CN=eiam,DC=lds,DC=eiam-a,DC=admin,DC=ch" --from-literal=ldapPassword="(c}Enf%mvVt6"
timeout 5
exit
