apiVersion: v1
kind: Secret
metadata:
  name: icp4adeploy-workspace-aae-app-engine-admin-secret
type: Opaque
stringData: 
  AE_DATABASE_PWD: "gdDDyzK69SDA2AYnS5Mm"
  AE_DATABASE_USER: "M_SSO_AE01"
  REDIS_PASSWORD: "password"
