kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ums-saml-data-pvc
  namespace: ibm-common-services
  annotations:
    trident.netapp.io/unixPermissions: "777"
spec:
  storageClassName: nas-ssd-basic
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi