apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    ciConfigurationChecksum: 268077aabd50dd457f29b9730c592342eb992b39
  creationTimestamp: "2021-11-16T10:42:41Z"
  labels:
    app.kubernetes.io/component: contentintegration-init
    app.kubernetes.io/instance: icp4adeploy-bawins1
    app.kubernetes.io/managed-by: Operator
    app.kubernetes.io/name: workflow-server
    app.kubernetes.io/version: 21.0.2
    release: 21.0.2
  name: icp4adeploy-bawins1-baw-content-init-job
  namespace: ssotest
  ownerReferences:
  - apiVersion: icp4a.ibm.com/v1
    kind: ICP4ACluster
    name: icp4adeploy
    uid: ef2680be-27d0-44eb-9e98-25455d453ba5
  resourceVersion: "75397108"
  uid: 4de75465-9e71-4e09-8f0f-9693b3147030
spec:
  backoffLimit: 30
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
  template:
    metadata:
      annotations:
        cloudpakId: 94a9c8c358bb43ba8fbdea62e7e166a5
        cloudpakName: IBM Cloud Pak for Business Automation
        cloudpakVersion: 21.0.2
        productChargedContainers: ""
        productCloudpakRatio: "1:1"
        productID: b592babf10c14f7197f70e198ac2676a
        productMetric: VIRTUAL_PROCESSOR_CORE
        productName: Non Chargeable Component - CP4BA
        productVersion: 21.0.2
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: contentintegration-init
        app.kubernetes.io/instance: icp4adeploy-bawins1
        app.kubernetes.io/managed-by: Operator
        app.kubernetes.io/name: workflow-server
        app.kubernetes.io/version: 21.0.2
        job-name: icp4adeploy-bawins1-baw-content-init-job
        release: 21.0.2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      - args:
        - /home/config/config-script.sh
        command:
        - sh
        - -c
        env:
        - name: CPE_URL
          value: https://icp4adeploy-cpe-svc:9443/wsi/FNCEWS40MTOM
        - name: IS_SECURE
          value: T
        - name: DOMAIN_NAME
          value: P8SSOTest
        - name: OBJECTSTORE_NAME
          value: SUFASBAWDOCS01
        - name: EVENTHANDLER_PATH
          value: /home/config/docs-config
        - name: BPMCALLBACK_URL
          value: https://icp4adeploy-bawins1-baw-service:9443/rest/bpm/wle
        - name: CPE_USERNAME
          valueFrom:
            secretKeyRef:
              key: appLoginUsername
              name: ibm-fncm-secret
        - name: CPE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: appLoginPassword
              name: ibm-fncm-secret
        - name: Enable_EventHandler
          value: "true"
        image: cp.icr.io/cp/cp4a/baw/iaws-ps-content-integration@sha256:e3389aafca0fb876c0c691c05c0289d3fe558db6b202d7dc0fb692e91bae3276
        imagePullPolicy: IfNotPresent
        name: contentintegration-init-job
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /shared/resources/cert-trusted
          name: trust-tls-volume
        - mountPath: /logs/application
          name: logs
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: icp4adeploy-bawins1-baw-server-sa
      serviceAccountName: icp4adeploy-bawins1-baw-server-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - name: trust-tls-volume
        projected:
          defaultMode: 511
          sources:
          - secret:
              items:
              - key: tls.crt
                path: ca.crt
              name: icp4a-root-ca
      - name: logs
        persistentVolumeClaim:
          claimName: icp4adeploy-bawins1-baw-logs-storage-pvc
status:
  active: 1
  startTime: "2021-11-16T10:42:41Z"
